// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: prefixServer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID            uint64    `protobuf:"fixed64,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	NodeIPv6          []byte    `protobuf:"bytes,2,opt,name=nodeIPv6,proto3" json:"nodeIPv6,omitempty"`
	Generation        uint32    `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Prefixes          []*Prefix `protobuf:"bytes,4,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	WithdrawnPrefixes []*Prefix `protobuf:"bytes,5,rep,name=withdrawnPrefixes,proto3" json:"withdrawnPrefixes,omitempty"`
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prefixServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_prefixServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_prefixServer_proto_rawDescGZIP(), []int{0}
}

func (x *CommandMessage) GetNodeID() uint64 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *CommandMessage) GetNodeIPv6() []byte {
	if x != nil {
		return x.NodeIPv6
	}
	return nil
}

func (x *CommandMessage) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *CommandMessage) GetPrefixes() []*Prefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *CommandMessage) GetWithdrawnPrefixes() []*Prefix {
	if x != nil {
		return x.WithdrawnPrefixes
	}
	return nil
}

type Prefix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to PrefixIP:
	//
	//	*Prefix_V4
	//	*Prefix_V6
	PrefixIP     isPrefix_PrefixIP `protobuf_oneof:"prefixIP"`
	PrefixLength uint32            `protobuf:"varint,3,opt,name=prefixLength,proto3" json:"prefixLength,omitempty"`
	L3ID         uint32            `protobuf:"varint,4,opt,name=l3ID,proto3" json:"l3ID,omitempty"`
	NextHop      []byte            `protobuf:"bytes,5,opt,name=nextHop,proto3" json:"nextHop,omitempty"`
}

func (x *Prefix) Reset() {
	*x = Prefix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prefixServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefix) ProtoMessage() {}

func (x *Prefix) ProtoReflect() protoreflect.Message {
	mi := &file_prefixServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefix.ProtoReflect.Descriptor instead.
func (*Prefix) Descriptor() ([]byte, []int) {
	return file_prefixServer_proto_rawDescGZIP(), []int{1}
}

func (m *Prefix) GetPrefixIP() isPrefix_PrefixIP {
	if m != nil {
		return m.PrefixIP
	}
	return nil
}

func (x *Prefix) GetV4() uint32 {
	if x, ok := x.GetPrefixIP().(*Prefix_V4); ok {
		return x.V4
	}
	return 0
}

func (x *Prefix) GetV6() []byte {
	if x, ok := x.GetPrefixIP().(*Prefix_V6); ok {
		return x.V6
	}
	return nil
}

func (x *Prefix) GetPrefixLength() uint32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

func (x *Prefix) GetL3ID() uint32 {
	if x != nil {
		return x.L3ID
	}
	return 0
}

func (x *Prefix) GetNextHop() []byte {
	if x != nil {
		return x.NextHop
	}
	return nil
}

type isPrefix_PrefixIP interface {
	isPrefix_PrefixIP()
}

type Prefix_V4 struct {
	V4 uint32 `protobuf:"fixed32,1,opt,name=v4,proto3,oneof"`
}

type Prefix_V6 struct {
	V6 []byte `protobuf:"bytes,2,opt,name=v6,proto3,oneof"`
}

func (*Prefix_V4) isPrefix_PrefixIP() {}

func (*Prefix_V6) isPrefix_PrefixIP() {}

var File_prefixServer_proto protoreflect.FileDescriptor

var file_prefixServer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x50, 0x65, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x22, 0xd8, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x50, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x50, 0x76, 0x36, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52,
	0x08, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x11, 0x77, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x11, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0x8a, 0x01, 0x0a,
	0x06, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x10, 0x0a, 0x02, 0x76, 0x34, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x07, 0x48, 0x00, 0x52, 0x02, 0x76, 0x34, 0x12, 0x10, 0x0a, 0x02, 0x76, 0x36, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x02, 0x76, 0x36, 0x12, 0x22, 0x0a, 0x0c, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x33, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c,
	0x33, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x48, 0x6f, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x48, 0x6f, 0x70, 0x42, 0x0a, 0x0a,
	0x08, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x49, 0x50, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prefixServer_proto_rawDescOnce sync.Once
	file_prefixServer_proto_rawDescData = file_prefixServer_proto_rawDesc
)

func file_prefixServer_proto_rawDescGZIP() []byte {
	file_prefixServer_proto_rawDescOnce.Do(func() {
		file_prefixServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_prefixServer_proto_rawDescData)
	})
	return file_prefixServer_proto_rawDescData
}

var file_prefixServer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prefixServer_proto_goTypes = []interface{}{
	(*CommandMessage)(nil), // 0: PeerManager.CommandMessage
	(*Prefix)(nil),         // 1: PeerManager.Prefix
}
var file_prefixServer_proto_depIdxs = []int32{
	1, // 0: PeerManager.CommandMessage.prefixes:type_name -> PeerManager.Prefix
	1, // 1: PeerManager.CommandMessage.withdrawnPrefixes:type_name -> PeerManager.Prefix
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_prefixServer_proto_init() }
func file_prefixServer_proto_init() {
	if File_prefixServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prefixServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prefixServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prefix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_prefixServer_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Prefix_V4)(nil),
		(*Prefix_V6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prefixServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prefixServer_proto_goTypes,
		DependencyIndexes: file_prefixServer_proto_depIdxs,
		MessageInfos:      file_prefixServer_proto_msgTypes,
	}.Build()
	File_prefixServer_proto = out.File
	file_prefixServer_proto_rawDesc = nil
	file_prefixServer_proto_goTypes = nil
	file_prefixServer_proto_depIdxs = nil
}
